<a href="https://colab.research.google.com/github/sarismejiasanchez/Pandas-NumPy/blob/main/Creando_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Generar una lista con valores haciendo uso de la funcion `range`

In [2]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Creando un array desde NumPy `np.arange(dato inicial, dato final, step)`

In [4]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Definir arrays en ceros

In [8]:
np.zeros(3)

array([0., 0., 0.])

Estos son muy utilizados para crear esquemas previos.
Ej: Si la dimensión que tengo de una imagen es de 10x10, genero un array de tipo matricial de 10x10, hecho netamente con valores de 0.

In [9]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Para los mismos propósitos que `np.zeros` podemos hacer uso de `np.ones`

In [10]:
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Generamos una distribucion normalizada, una disribución totalmente ordenada, de los números desde un rango inferior hasta un rango superior. `np.linspace(valor inicial, valor final, numero de datos a generar)` haciendo una distribucion desde el inicio hasta el fin, basada en los datos.

In [12]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

Generar una matriz de la dimensión indicada, con la diagonal principal en 1

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Generar valores totalmente aleatorios

In [15]:
np.random.rand() # Genera un valor aleatorio entre 0 y 1

0.2691607902319756

In [17]:
np.random.rand(4) # Genera un array de 4 dimensiones con valores aleatorios entre 0 y 1

array([0.16255767, 0.79297969, 0.79840982, 0.28372229])

In [18]:
np.random.rand(4, 4) # Genera una estructura matricial con valores totalmente aleatorios

array([[0.51991088, 0.2550493 , 0.10160263, 0.48222437],
       [0.33726754, 0.00219651, 0.42353154, 0.87929536],
       [0.84119491, 0.47132447, 0.55457768, 0.8611829 ],
       [0.05214372, 0.97935213, 0.49768749, 0.48920013]])

In [19]:
np.random.randint(1, 15) # Genera un entero aleatorio dentro del rango dado

4

In [20]:
np.random.randint(1, 100, [10, 10]) # Genera una tupla de 10x10 con valores aleatorios entre 1 y 100

array([[66, 44, 32, 68, 83, 66, 39, 81, 49, 22],
       [ 6, 74, 34,  2, 20, 83, 44,  4, 90,  3],
       [68, 91, 69, 16, 72, 18, 25, 39, 44, 42],
       [70, 14, 13, 94, 76,  7, 46, 38, 71, 21],
       [71, 84, 86, 74, 49, 32, 95, 67, 61, 38],
       [22, 12, 23, 38, 45, 88,  5, 89, 67, 64],
       [42, 30, 17, 76, 76, 26, 74, 63, 93, 50],
       [10, 18, 81, 55, 45, 73, 44, 32, 18, 87],
       [ 2, 32, 69, 38, 69, 91, 24, 95, 89, 72],
       [37, 83, 63, 84, 15, 98, 83, 38, 59, 59]])