<a href="https://colab.research.google.com/github/sarismejiasanchez/Pandas-NumPy/blob/main/NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
arr = np.array(lista)

In [7]:
type(arr)

numpy.ndarray

In [11]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##Indexing

Los array a nivel de indexado, empiezan desde 0 y no desde 1

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[1]

2

In [22]:
arr[0] + arr[5]

7

In [23]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
matriz[0] # Ingresa a la primer posición a nivel de filas

array([1, 2, 3])

In [25]:
matriz[1]

array([4, 5, 6])

In [26]:
matriz[0, 2] # Primer valor = Filas, segundo valor = Columnas

3

## Slicing
Accediendo a múltiples valores en un array

In [27]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[0:3] # Accediendo a mas de un objeto (desde la posición 0 hasta la posicion 3 sin incluir el limite)

array([1, 2, 3])

In [36]:
arr[1:6] 

array([2, 3, 4, 5, 6])

In [37]:
arr[:6] # Desde la posicion 0 hasta la posicion 6

array([1, 2, 3, 4, 5, 6])

In [38]:
arr[2:] # Desde la posicion 2 hasta el final

array([3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[::3] # Todo de 3 en 3 (Seleccion por pasos)

array([1, 4, 7])

In [44]:
arr[-1] # El primer valor del final hacia el comienzo

9

In [43]:
arr[-3:] # Desde el tercer valor final hasta el comienzo

array([7, 8, 9])

In [45]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
matriz[1:] # Desde la fila 1 hacia adelante

array([[4, 5, 6],
       [7, 8, 9]])

In [49]:
matriz[1:, 0:2] # Desde la fila 1, columna 0 hasta la 2 (no incluye limite)

array([[4, 5],
       [7, 8]])