<a href="https://colab.research.google.com/github/sarismejiasanchez/Pandas-NumPy/blob/main/Shape_y_Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [9]:
# Generamos un array con numeros aleatorios entre 1 y 10, en una estructura de 3x2
arr = np.random.randint(1, 10, (3, 2))

Hay 2 funciones muy importantes de los arreglos (Shape y Reshape). La forma de un arreglo nos va a decir con que estructura se está trabajando (tamaño, manipular, ingresar).

# Shape
Indica la forma del arreglo.

In [12]:
arr.shape

(3, 2)

In [13]:
arr

array([[3, 7],
       [2, 6],
       [1, 5]])

# Reshape
transforma el arreglo mientras se mantengan los elementos.

In [14]:
arr.reshape(1, 6)

array([[3, 7, 2, 6, 1, 5]])

In [16]:
arr.reshape(2, 3)

array([[3, 7, 2],
       [6, 1, 5]])

In [17]:
np.reshape(arr, (1, 6))

array([[3, 7, 2, 6, 1, 5]])

In [18]:
# Haciendo reshape como lo haría C
# Ordena tomando filas
np.reshape(arr, (1, 6), 'C') # Este es el lenguaje recomendado, el cual es la base de Python para la transformación de los arreglos

array([[3, 7, 2, 6, 1, 5]])

In [20]:
arr

array([[3, 7],
       [2, 6],
       [1, 5]])

In [19]:
# Haciendo reshape como lo haría Fortran
# Ordena por Columnas
np.reshape(arr, (2, 3), 'F')

array([[3, 1, 6],
       [2, 7, 5]])

In [21]:
# Además, existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en C.
np.reshape(arr, (2, 3), 'A')

array([[3, 7, 2],
       [6, 1, 5]])

No puedes cambiar la "forma" a la "forma" original del array, si tienes un (3,3) no lo puedes pasar a (4,2). 
No respeta los 9 elementos del array original

In [22]:
arr

array([[3, 7],
       [2, 6],
       [1, 5]])

In [23]:
arr.reshape(2, 4)

ValueError: ignored

# Reto
- Crear un array de cualquier dimensión y cambiar sus dimensiones.

In [29]:
# Generamos un array con numeros aleatorios entre 1 y 50, en una estructura de 2x4
arr = np.random.randint(1, 50, (2, 4))

In [32]:
arr

array([[48,  6,  5, 39],
       [ 4, 46, 49, 17]])

In [31]:
arr.reshape(1, 8)

array([[48,  6,  5, 39,  4, 46, 49, 17]])

In [33]:
np.reshape(arr, (1, 8), 'C')

array([[48,  6,  5, 39,  4, 46, 49, 17]])

- Intenta cambiar el array de forma que no respete la estructura original

In [34]:
np.reshape(arr, (3, 3), 'C')

ValueError: ignored