<a href="https://colab.research.google.com/github/sarismejiasanchez/Pandas-NumPy/blob/main/Tipos_de_Datos_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Los arrays de NumPy solo pueden contener un tipo de dato, ya que esto es lo que le confiere las ventajas de la optimización de memoria.

El array de Numpy únicamente puede tener un único tipo de datos en el cual va a trabajar. No puedo tener la mitad del array en int y la otra mitad en bool.

In [1]:
import numpy as np

In [14]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [16]:
arr.dtype # Muestra el tipo de dato que esta manejando el array

dtype('int64')

In [17]:
arr = np.array([1, 2, 3, 4], dtype = 'float64') # Definir array con dtype = 'float64'
arr.dtype

dtype('float64')

In [20]:
arr

array([1., 2., 3., 4.])

In [25]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [26]:
arr.astype(np.float64) # Cnvertirlo de 'int64' a 'float64

array([1., 2., 3., 4.])

In [31]:
arr = np.array([0, 1, 2, 3, 4])
arr.astype(np.bool_) # Convertirlo a bool

array([False,  True,  True,  True,  True])

In [34]:
arr = np.array([0, 1, 2, 3, 4])
arr.astype(np.string_) # Convertirlo a string

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [35]:
arr = np.array(['0', '1', '2', '3', '4'])
arr.astype(np.int8) # Convertirlo a int8

array([0, 1, 2, 3, 4], dtype=int8)

In [36]:
arr = np.array(['hola','1','2','3','4'])
arr.astype(np.int8)

ValueError: ignored

In [39]:
z = np.arange(10, dtype=np.uint8)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [38]:
np.power(100, 8, dtype=np.int64)

10000000000000000

In [40]:
np.power(100, 8, dtype=np.int32)

1874919424